{"name": "test_absolute_fail[10-ValueError]", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nValueError: The argument must be an integer", "trace": "value = '10', expected = <class 'ValueError'>\n\n    @allure.feature('Calculator')\n    @allure.story('Absolute')\n    @pytest.mark.xfail\n    @pytest.mark.parametrize('value,expected', [\n        (None, ValueError),\n        ('10', ValueError),\n        ('-10', ValueError),\n        (None, ValueError)\n    ])\n    def test_absolute_fail(value, expected):\n>       assert calc.absolute(value) == expected\n\ntests/test_absolute.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <src.calculator.Calculator object at 0x101d9a030>, value = '10'\n\n    def absolute(self, value):\n        if not isinstance(value, int):\n>           raise ValueError(\"The argument must be an integer\")\nE           ValueError: The argument must be an integer\n\nsrc/calculator.py:43: ValueError"}, "parameters": [{"name": "value", "value": "'10'"}, {"name": "expected", "value": "<class 'ValueError'>"}], "start": 1721305183656, "stop": 1721305183656, "uuid": "e1373610-1d9f-4fb0-9a98-fbbb77dfdd09", "historyId": "06a78f6ae6c405cb2bbe95a409e6be27", "testCaseId": "4d0aebbc8408ddb0c54381d4b3dcfb02", "fullName": "tests.test_absolute#test_absolute_fail", "labels": [{"name": "feature", "value": "Calculator"}, {"name": "story", "value": "Absolute"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_absolute"}, {"name": "host", "value": "Derrys-MacBook-Air.local"}, {"name": "thread", "value": "4225-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_absolute"}]}