{"name": "test_absolute_fail[None-ValueError0]", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nValueError: The argument must be an integer", "trace": "value = None, expected = <class 'ValueError'>\n\n    @allure.feature('Calculator')\n    @allure.story('Absolute')\n    @pytest.mark.xfail\n    @pytest.mark.parametrize('value,expected', [\n        (None, ValueError),\n        ('10', ValueError),\n        ('-10', ValueError),\n        (None, ValueError)\n    ])\n    def test_absolute_fail(value, expected):\n>       assert calc.absolute(value) == expected\n\ntests/test_absolute.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <src.calculator.Calculator object at 0x103b71b20>, value = None\n\n    def absolute(self, value):\n        if not isinstance(value, int):\n>           raise ValueError(\"The argument must be an integer\")\nE           ValueError: The argument must be an integer\n\nsrc/calculator.py:43: ValueError"}, "parameters": [{"name": "value", "value": "None"}, {"name": "expected", "value": "<class 'ValueError'>"}], "start": 1721307283399, "stop": 1721307283399, "uuid": "ab4c13cd-e398-4ee5-b512-be2f0c9a1ef6", "historyId": "ee598e551facf6fadb8dcb2500ddaf24", "testCaseId": "4d0aebbc8408ddb0c54381d4b3dcfb02", "fullName": "tests.test_absolute#test_absolute_fail", "labels": [{"name": "feature", "value": "Calculator"}, {"name": "story", "value": "Absolute"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_absolute"}, {"name": "host", "value": "Derrys-MacBook-Air.local"}, {"name": "thread", "value": "6143-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_absolute"}]}