{"name": "test_divide_fail[None-2-ValueError]", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nValueError: Both arguments must be integers", "trace": "x = None, y = 2, expected = <class 'ValueError'>\n\n    @allure.feature('Calculator')\n    @allure.story('Division')\n    @pytest.mark.xfail\n    @pytest.mark.parametrize('x,y,expected', [\n        (None, None, ValueError),\n        (10, None, ValueError),\n        (None, 2, ValueError),\n        (10, '2', ValueError),\n        ('10', 2, ValueError),\n        (10, 0, ValueError)\n    ])\n    def test_divide_fail(x, y, expected):\n>       assert calc.divide(x, y) == expected\n\ntests/test_divide.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <src.calculator.Calculator object at 0x10273bcb0>, value1 = None, value2 = 2\n\n    def divide(self, value1, value2):\n        if not (isinstance(value1, int) and isinstance(value2, int)):\n>           raise ValueError(\"Both arguments must be integers\")\nE           ValueError: Both arguments must be integers\n\nsrc/calculator.py:24: ValueError"}, "parameters": [{"name": "x", "value": "None"}, {"name": "y", "value": "2"}, {"name": "expected", "value": "<class 'ValueError'>"}], "start": 1721305183741, "stop": 1721305183741, "uuid": "27e58b0d-a54f-4ebe-8cc1-a098df7f5ce1", "historyId": "f3860f4377023724eb106608245f4197", "testCaseId": "2176d9cf6af895bcdf6b05e1fff967c7", "fullName": "tests.test_divide#test_divide_fail", "labels": [{"name": "story", "value": "Division"}, {"name": "feature", "value": "Calculator"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_divide"}, {"name": "host", "value": "Derrys-MacBook-Air.local"}, {"name": "thread", "value": "4225-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_divide"}]}